<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DarkKitchen.Importers.Contracts\DarkKitchen.Importers.Contracts.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>

  <Target Name="CopyToPlugins" AfterTargets="Build">
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(MSBuildThisFileDirectory)../DarkKitchen.WebApi/bin/$(Configuration)/$(TargetFramework)/Plugins" />
  </Target>

</Project>
