<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DarkKitchen.Domain\DarkKitchen.Domain.csproj" />
    <ProjectReference Include="..\DarkKitchen.DTOs\DarkKitchen.DTOs.csproj" />
    <ProjectReference Include="..\DarkKitchen.IBusinessLogic\DarkKitchen.IBusinessLogic.csproj" />
    <ProjectReference Include="..\DarkKitchen.IDataAccess\DarkKitchen.IDataAccess.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Security\" />
    <Folder Include="Shipping\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
